### PR TITLE
Add a callback to notify of proxy successfully initialized in lantern-mobile

### LINKED ISSUE #2892: Add a callback or similar from Go to Java when actually proxying

### LINKED ISSUE #2908: Version of Gomobile required for Java callbacks produces panic
The panic is identified and can be fixed on our side.
```
V/DEBUG   (12399): Attempt to run client proxy on :9192
D/dalvikvm(12399): Trying to load lib /data/app-lib/org.getlantern.flashlighttester-2/libgojni.so 0x4134dac0
D/dalvikvm(12399): Added shared lib /data/app-lib/org.getlantern.flashlighttester-2/libgojni.so 0x4134dac0
D/dalvikvm(12399): No JNI_OnLoad found in /data/app-lib/org.getlantern.flashlighttester-2/libgojni.so 0x4134dac0, skipping init
E/Go      (12399): panic: Unable to determine user's home directory: user: Current not implemented on android/arm
E/Go      (12399): goroutine 1 [running]:
E/Go      (12399): github.com/getlantern/appdir.InHomeDir(0x6f32d4f0, 0x8, 0x0, 0x0)
E/Go      (12399): 	/src/github.com/getlantern/appdir/appdir.go:25 +0x108
E/Go      (12399): github.com/getlantern/appdir.general(0x5ef37978, 0x7, 0x0, 0x0)
E/Go      (12399): 	/src/github.com/getlantern/appdir/appdir_linux.go:14 +0x100
E/Go      (12399): github.com/getlantern/appdir.General(0x5ef37978, 0x7, 0x0, 0x0)
E/Go      (12399): 	/src/github.com/getlantern/appdir/appdir.go:14 +0x30
E/Go      (12399): github.com/getlantern/flashlight/packaged.init()
E/Go      (12399): 	/src/github.com/getlantern/flashlight/packaged/packaged.go:37 +0xb8
E/Go      (12399): github.com/getlantern/flashlight/ui.init()
E/Go      (12399): 	/src/github.com/getlantern/flashlight/ui/ws.go:164 +0x6c
E/Go      (12399): github.com/getlantern/flashlight/geolookup.init()
E/Go      (12399): 	/src/github.com/getlantern/flashlight/geolookup/geolookup.go:137 +0x74
E/Go      (12399): github.com/getlantern/flashlight/client.init()
E/Go      (12399): 	/src/github.com/getlantern/flashlight/client/stats.go:40 +0x90
E/Go      (12399): github.com/getlantern/lantern-mobile.init()
E/Go      (12399): 	/src/github.com/getlantern/lantern-mobile/masquerades.go:2221 +0x5c
E/Go      (12399): _/tmp/gomobile-work-263273048/go_client.init()
E/Go      (12399): 	/tmp/gomobile-work-263273048/go_client/go_clientmain.go:70 +0x4c
E/Go      (12399): main.init()
E/Go      (12399): 	/tmp/gomobile-work-263273048/androidlib/main.go:9 +0x50
E/Go      (12399): goroutine 17 [chan receive, locked to thread]:
E/Go      (12399): runtime.gopark(0x5efc90c0, 0x6f330070, 0x5ef5e3f0, 0xc, 0x17, 0x3)
E/Go      (12399): 	/go/src/runtime/proc.go:185 +0x148
E/Go      (12399): runtime.goparkunlock(0x6f330070, 0x5ef5e3f0, 0xc, 0x17, 0x3)
E/Go      (12399): 	/go/src/runtime/proc.go:191 +0x44
E/Go      (12399): runtime.chanrecv(0x5eea22d0, 0x6f330040, 0x0, 0x5ec09901, 0x5ebb0000)
E/Go      (12399): 	/go/src/runtime/chan.go:448 +0x4b8
E/Go      (12399): runtime.chanrecv1(0x5eea22d0, 0x6f330040, 0x0)
E/Go      (12399): 	/go/src/runtime/chan.go:349 +0x28
E/Go      (12399): runtime.cgocallbackg1()
E/Go      (12399): 	/go/src/runtime/cgocall.go:196 +0x7c
E/Go      (12399): runtime.cgocallbackg()
E/Go      (12399): 	/go/src/runtime/cgocall.go:177 +0xac
E/Go      (12399): runtime.cgocallback_gofunc(0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/runtime/asm_arm.s:609 +0x6c
E/Go      (12399): runtime.goexit()
E/Go      (12399): 	/go/src/runtime/asm_arm.s:1016 +0x4
E/Go      (12399): goroutine 18 [syscall, locked to thread]:
E/Go      (12399): runtime.goexit()
E/Go      (12399): 	/go/src/runtime/asm_arm.s:1016 +0x4
E/Go      (12399): goroutine 5 [syscall]:
E/Go      (12399): syscall.Syscall(0x3, 0x31, 0x6f358000, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/syscall/asm_linux_arm.s:17 +0x8
E/Go      (12399): syscall.read(0x31, 0x6f358000, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/syscall/zsyscall_linux_arm.go:783 +0x78
E/Go      (12399): syscall.Read(0x31, 0x6f358000, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/syscall/syscall_unix.go:160 +0x4c
E/Go      (12399): os.(*File).read(0x6f2ec158, 0x6f358000, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/os/file_unix.go:211 +0x54
E/Go      (12399): os.(*File).Read(0x6f2ec158, 0x6f358000, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/os/file.go:95 +0x7c
E/Go      (12399): bufio.(*Reader).fill(0x6f2f7f7c)
E/Go      (12399): 	/go/src/bufio/bufio.go:97 +0x1c4
E/Go      (12399): bufio.(*Reader).ReadSlice(0x6f2f7f7c, 0x40a, 0x0, 0x0, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/bufio/bufio.go:328 +0x264
E/Go      (12399): bufio.(*Reader).ReadLine(0x6f2f7f7c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/bufio/bufio.go:357 +0x60
E/Go      (12399): golang.org/x/mobile/internal/mobileinit.lineLog(0x6f2ec158, 0x6)
E/Go      (12399): 	/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:50 +0xe0
E/Go      (12399): created by golang.org/x/mobile/internal/mobileinit.init.1
E/Go      (12399): 	/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:74 +0x104
E/Go      (12399): goroutine 6 [syscall]:
E/Go      (12399): syscall.Syscall(0x3, 0x36, 0x6f358400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/syscall/asm_linux_arm.s:17 +0x8
E/Go      (12399): syscall.read(0x36, 0x6f358400, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/syscall/zsyscall_linux_arm.go:783 +0x78
E/Go      (12399): syscall.Read(0x36, 0x6f358400, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/syscall/syscall_unix.go:160 +0x4c
E/Go      (12399): os.(*File).read(0x6f2ec168, 0x6f358400, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/os/file_unix.go:211 +0x54
E/Go      (12399): os.(*File).Read(0x6f2ec168, 0x6f358400, 0x400, 0x400, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/os/file.go:95 +0x7c
E/Go      (12399): bufio.(*Reader).fill(0x6f2f877c)
E/Go      (12399): 	/go/src/bufio/bufio.go:97 +0x1c4
E/Go      (12399): bufio.(*Reader).ReadSlice(0x6f2f877c, 0x40a, 0x0, 0x0, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/bufio/bufio.go:328 +0x264
E/Go      (12399): bufio.(*Reader).ReadLine(0x6f2f877c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
E/Go      (12399): 	/go/src/bufio/bufio.go:357 +0x60
E/Go      (12399): golang.org/x/mobile/internal/mobileinit.lineLog(0x6f2ec168, 0x4)
E/Go      (12399): 	/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:50 +0xe0
E/Go      (12399): created by golang.org/x/mobile/internal/mobileinit.init.1
E/Go      (12399): 	/src/golang.org/x/mobile/internal/mobileinit/mobileinit_android.go:81 +0x194
```

### LINKED ISSUE #2916: panic: Unable to determine user's home directory: user: Current not implemented on android/arm
Built a fresh copy of the library while I was working on https://github.com/getlantern/lantern-mobile/issues/3 and the app crashes immediately with the following: 

```
D/LanternMainActivity(18919): Starting Lantern...
D/dalvikvm(18919): Trying to load lib /data/app-lib/org.getlantern.lantern-34/libgojni.so 0x424ff290
W/linker  (18919): libgojni.so has text relocations. 
This is wasting memory and is a security risk. Please fix.
D/dalvikvm(18919): Added shared lib /data/app-lib/org.getlantern.lantern-34/libgojni.so 0x424ff290
D/dalvikvm(18919): No JNI_OnLoad found in 
/data/app-lib/org.getlantern.lantern-34/libgojni.so 0x424ff290, skipping init
E/Go      (18919): panic: Unable to determine user's home directory: 
user: Current not implemented on android/arm
E/Go      (18919): goroutine 1 [running]:
E/Go      (18919): github.com/getlantern/appdir.InHomeDir(0x8ad01500, 0x8, 0x0, 0x0)
````

### PR DESCRIPTION
**Pull request by uaalto**
Closes #2892 
Closes #2908 
Closes #2916 

I will open a PR with to make Firetweet API-compatible, without changing any functionality there ATM.

### CODE REVIEW

**Comment by uaalto** [comment]
Sorry @xiam, I had to rewrite history of this branch because I added the gomobile dependencies as submodules and couldn't remove it without doing so. You probably need to do a clean pull of the branch.

**Comment by xiam** [comment]
Got it @uaalto, thanks!

**Comment by xiam** [comment]
Oops, closed by mistake.

**Comment by xiam** [comment]
Tests are failing on this PR:

```
# github.com/getlantern/lantern-mobile
src/github.com/getlantern/lantern-mobile/interface_test.go:74: not enough arguments in call to RunClientProxy
src/github.com/getlantern/lantern-mobile/interface_test.go:94: not enough arguments in call to RunClientProxy
```

**Comment by uaalto** [comment]
Yes, thank you. I realized when I pushed on Travis, which wasn't working half an hour ago. I'm fixing them ATM.

**Comment by xiam** [comment]
Thanks @uaalto, this is both compiling and working fine for me.

**Pull request merged**
