### PR TITLE
Merge release

### PR DESCRIPTION
**Pull request by oxtoacart**
I've merged the latest from release-2.0.1 into valencia.

### CODE REVIEW

**Comment by myleshorton** [comment]
What's the difference between this and https://github.com/getlantern/lantern/pull/3561 @oxtoacart?

**Comment by oxtoacart** [comment]
Haha, great minds think alike!  I just hadn't noticed #3561.  FWIW, #3561 has merge conflicts, whereas #3562 does not.

**Comment by oxtoacart** [comment]
@myleshorton I also noticed some test failures - I think I've fixed them now, but need to wait for Travis to finish.

**Comment by myleshorton** [comment]
=) Nice! Actually how did you generate your PR? For whatever reason when I just went to merge release-2.0.1 to valencia it was much more massive. What did you do differently on your merge branch?

**Comment by myleshorton** [comment]
We'll also need to do whatever your process is one last time, as there were at least two additional merges to release-2.0.1. I'll merge this one now though!

**Comment by oxtoacart** [comment]
@myleshorton I branched off valencia and then merged the release branch into this new branch, manually resolving conflicts.

**Comment by myleshorton** [comment]
Gotcha -- ok cool makes sense. Thanks @oxtoacart!

**Comment by oxtoacart** [comment]
It's not clear to me why your PR had so many more changes.  Looking at a [diff](https://github.com/getlantern/lantern/compare/release-2.0.1) from release-2.0.1 to valencia now, it shows relatively few new changes.  Mysterious.

**Pull request merged**
