### PR TITLE
Adds severity level to logs closes #2589

### LINKED ISSUE #2589: Add severity level to logs
This is useful for knowing, for example, if you've encountered any errors during a test run of Lantern.

### PR DESCRIPTION
**Pull request by myleshorton**
This is just a quick change to logging so we know the severity level (TRACE, DEGUG, ERROR, FATAL) in log files

### CODE REVIEW

**Comment by myleshorton** [comment]
Can you take a peek at this one @xiam?

**Comment by myleshorton** [comment]
I'll fix the tests =).

**Comment by xiam** [comment]
Sure!

**Comment by myleshorton** [comment]
More fixes coming =).

**Comment by myleshorton** [comment]
Looks like this finally passes tests @xiam

**Comment by xiam** [comment]
Hey @myleshorton,

Seems like you are also adding unrelated stuff to the repo:

```
git diff --name-only issue2589 valencia
```

See the freetype and Go stuff.

This is probably due to this gost bug: https://github.com/getlantern/gost/issues/2

**Comment by xiam** [comment]
Looks like `github.com/rogpeppe/godef` and `9fans.net/go` were added too, what do we need them for?   `github.com/rogpeppe/godef` depends on `9fans.net/go`, but no other package depends on `github.com/roggpeppe/godef`.

**Comment by myleshorton** [comment]
Yeah wow good catch @xiam. Most of those are actually tools vim-go uses. I'll create a new PR.

**Comment by myleshorton** [comment]
And you're totally right it's because of that bug -- it's a pretty annoying one!

**Pull request closed without merging**
