### PR TITLE
New UI page

### PR DESCRIPTION
**Pull request by atavism**
This replaces the map with a new page that informs the user Lantern is running and provides a list of recommended sites.

### CODE REVIEW

**Comment by atavism** [comment]
Actually, you had a manoto branch I should merge to, right @myleshorton?

**Comment by myleshorton** [comment]
Awesome! No worries on the manoto branch. I'll just merge that in separately. I'll try to merge this one in today.

**Comment by myleshorton** [comment]
LGTM, and I'll go ahead and merge for now. The screenshot are huge and will add a lot to the download, but we can merge new ones in if/when we get smaller ones sent over.

**Comment by atavism** [comment]
We can remove all the map stuff now too, but I wanted to create a separate PR for that. That should reduce the download size.

**Comment by myleshorton** [comment]
Yeah we'll want that still in there for give mode though @atavism. We could to two separate builds, but that would complicate things.

We ultimately can just put it all on our server though and should be good then.

**Pull request merged**
