### PR TITLE
Delete old registry system startup setting closes #2791

### LINKED ISSUE #2791: Lantern opens automatically after restart even when "Run Lantern automatically on Startup" is disabled - Windows 8.1, chrome
I tried two different scenarios. One with Lantern running while restarting and the other is after quitting Lantern. 

In both these scenarios, Lantern started automatically after restart.

### PR DESCRIPTION
**Pull request by myleshorton**

### CODE REVIEW

**Comment by myleshorton** [comment]
Hey @uaalto you mind taking a look at this one?

**Comment by xiam** [comment]
I'll take this one, if you don't mind @uaalto. It's related to the #2776 issue.

**Comment by xiam** [comment]
Merged! thanks @myleshorton

**Comment by myleshorton** [comment]
Thanks @xiam!

**Pull request merged**
