### PR TITLE
add 'SystemProxy' in Settings to resolve #3241

### LINKED ISSUE #3241: 致：开发者
致开发者：
这几天看了蓝灯社区近几个月的动态
蓝灯一直半死不活
个人推测主要原因是蓝灯默认开启ie代理，被某数字软件上报数据，导致ip被封。
要想蓝灯长远，开发商必须彻底关闭IE代理。
国外的开发商太不理解国内行情
细数国内的开发代理软件，有哪个是默认开IE代理的
说实话，蓝灯默认开ie代理，能存活这么长时间，我都佩服
美国政府的资助不是盖的。。。
但是开发商关闭IE代理，不仅对蓝灯本身有好处
对蓝灯用户也有好处
还有他那种yaml自带规则的做法，实在不可行
应该另建一个pac文本，指定规则
现在科学上网谁没有代理扩展程序
又有几个去开IE
还有proxifier等等。。。。。。﻿

### PR DESCRIPTION
**Pull request by kuun**
only code in flashlight, ui not included

### CODE REVIEW

**Comment by kuun** [comment]
Add option 'SystemProxy' in 'setttings' to support to disable auto setting system proxy.

@xiam we need this feature, specially in china. issues about this feature: #3615, #3241

**Comment by myleshorton** [comment]
Thanks for the @kuun -- we'll discuss this in more detail.

**Comment by myleshorton** [comment]
Closing this in favor of #3628 @kuun. Thanks!!

**Comment by kuun** [comment]
ok

**Comment by kuun** [comment]
@myleshorton ok, thanks

**Pull request closed without merging**
