### PR TITLE
uninstall previous version before install new one

### PR DESCRIPTION
**Pull request by fffw**
Resolvers https://github.com/getlantern/lantern/issues/2477

Oh I can't package windows installer for testing due to lack of BNS_CERT_PASS. Who has interest please test and revise directly.

### CODE REVIEW

**Comment by myleshorton** [comment]
I'll have a look at this thanks @fffw

**Comment by myleshorton** [comment]
Hey @fffw I just ended up making a few tweaks directly to this. The biggest was making the uninstall silent, as otherwise the use would have to manually press "OK" for the uninstall to complete before the install could start, which was confusing.

**Comment by fffw** [comment]
@myleshorton The flow is good in general. I changed a bit to remove superfluous `DetailPrint` in some cases. You can merge it if you think my changes are ok.

**Comment by myleshorton** [comment]
Looking good @fffw thanks!

**Pull request merged**
