### PR TITLE
Just removed file polling closes #3207

### LINKED ISSUE #3207: Lantern CPU usage too high
Pretty consistently at around 12% on OSX.

### PR DESCRIPTION
**Pull request by myleshorton**
Would be cool to get this into 2.0.10!!

### CODE REVIEW

**Comment by myleshorton** [comment]
You want to take a look @fffw or @aranhoide?

**Comment by myleshorton** [comment]
Looks like that remaining error is just with creating new CF distributions, which I think is OK.

**Comment by Trickister** [comment]
thanks

**Comment by Trickister** [comment]
how do it get started on this software stuff?

**Comment by fffw** [comment]
LGTM!

**Comment by myleshorton** [comment]
Awesome thanks @fffw!

**Pull request merged**
