### PR TITLE
Updated eventual so that it doesn't need goroutines and therefore can…

### PR DESCRIPTION
**Pull request by oxtoacart**
…'t leak goroutines

@fffw I've separated this from the detour stuff since it's not strictly related.

### CODE REVIEW

**Comment by fffw** [comment]
I'm wondering if we can use `sync.Cond` in place of slice of channels. Get() calls `cond.Wait()`, while Set/time.AfterFunc/Cancel calls `cond.Broadcast()`. It's unnecessary to pass the value through channel, as it can always be retrieved from `atomic.Value`.

Or, we can use single channel and always close it in `Set` and `Cancel`. All pending `Get` wait on it, and retrieve the actual value after `select`. Currently waiters are only notified once and get removed, single channel can do the same, but with less code and a little performance gain.

**Comment by oxtoacart** [comment]
I don't think having time.AfterFunc call cond.Broadcast() because that'll make other waiters stop even if they have a longer timeout.

I'll try the single channel thing though.

**Comment by oxtoacart** [comment]
Actually, a single channel won't work because we need to know how many waiters we have so that we send a message to each.  We could do a single channel plus an atomic counter of waiters, and then send a message for each waiter, but I don't know that this buys us much.

**Comment by fffw** [comment]
Oh, I didn't think about it. LGTM!

**Pull request merged**
