### PR TITLE
Updated Go 1.5 to release candidate 1

### PR DESCRIPTION
**Pull request by uaalto**
Should reduce instability issues: https://github.com/getlantern/firetweet/issues/147

### CODE REVIEW

**Comment by xiam** [comment]
Thanks @uaalto,

Have you seen this error?

```
gomobile: go build -p=4 -pkgdir=/pkg/gomobile/pkg_android_arm -tags="" -ldflags -w -buildmode=c-shared -o=/tmp/gomobile-work-268728515/android/src/main/jniLibs/armeabi-v7a/libgojni.so /tmp/gomobile-work-268728515/androidlib/main.go failed: exit status 1
/tmp/gomobile-work-268728515/androidlib/main.go:5:2: cannot find package "golang.org/x/mobile/bind/java" in any of:
	/go/src/golang.org/x/mobile/bind/java (from $GOROOT)
	/src/golang.org/x/mobile/bind/java (from $GOPATH)
/tmp/gomobile-work-268728515/go_client/go_clientmain.go:9:2: cannot find package "golang.org/x/mobile/bind/seq" in any of:
	/go/src/golang.org/x/mobile/bind/seq (from $GOROOT)
	/src/golang.org/x/mobile/bind/seq (from $GOPATH)

make: *** [android-lib] Error 1
```

**Comment by atavism** [comment]
I just tested this and it definitely resolves https://github.com/getlantern/firetweet/issues/147 -- I'm also not seeing that error, @xiam

**Comment by uaalto** [comment]
I think that error is caused by the lack of revision management in go get, @xiam. There is no way to tell `go get` to receive a specific version, but just get the last and checkout directly with git. The problem with that is if it fails before getting. But maybe the error you are getting can be resolved by a git checkout?

**Comment by uaalto** [comment]
Hey @xiam, I vendored the Gomobile dependencies, so you shouldn't have a version problem now.

**Comment by xiam** [comment]
Thanks! I'm going to try rebuilding it.

**Comment by xiam** [comment]
Works now. Thanks!

**Comment by uaalto** [comment]
Great! Thank you!

**Pull request merged**
