### PR TITLE
Using an explicit patch for Go

### PR DESCRIPTION
**Pull request by xiam**
If you're not using the Lantern's Go fork and you try to build it without docker it will fail:

* https://github.com/getlantern/lantern/issues/4638
* https://github.com/getlantern/lantern/issues/4605#issuecomment-224985945
* https://github.com/getlantern/lantern/issues/4692

For users there's no obvious indication of what happened. Some users could find out that our README changed a bit and that now we require a fork of Go but some others won't.

What I propose here is that `setenv` checks for the proper environment values and suggests what to do in case that the environment is not adequate (e.g.: when the user does not have our Go fork).

```
make linux
Lantern requires a special fork of Go, use 'make lantern-go'
make: *** [linux-386] Error 1
```

```
make lantern-go
# wait several minutes
```

```
make linux
# success!
```

The included patch was generated with https://github.com/getlantern/go/pull/2

### CODE REVIEW

**Comment by xiam** [comment]
Needs more work, travis is failing.

**Comment by xiam** [comment]
Travis is still failing but that's for a different reason than the code I added here, we have the same failure on devel.

Could you take a look @oxtoacart or @myleshorton?

**Comment by myleshorton** [comment]
Yup I've been noticing this too @xiam -- I'll dig deeper into it.

**Comment by oxtoacart** [comment]
Yeah, I'm seeing a failure too, lantern_test.go right?

**Comment by oxtoacart** [comment]
It's weird, according to travis, this commit was good - 9ab47f4105517d8c9b0bbfdfb06b448b0b0f37d6

I tried checking that out locally and running, and the test still fails, so I suspect that this is something that changed on the proxy side.

**Comment by xiam** [comment]
Thanks @oxtoacart, @myleshorton. PR is ready now.

**Comment by xiam** [comment]
We don't need this anymore.

**Comment by Kabibi** [comment]
@xiam What should I do next after downloading the patch? Or how to use?

**Comment by xiam** [comment]
Hey @Kabibi, calling `make` would have done the trick, but this is not required anymore.

**Comment by Kabibi** [comment]
I have tried "make lantern" and still have **"tr.MaxIdleTime undefined"** and **"tr.EnforceMaxIdleTime undefined"** errors. Now I have no idea how to make lantern successfully on my Opensuse. What do you mean by "this is not required anymore?" Can you give me more tips? Thank U so much! @xiam

**Pull request closed without merging**
