### PR TITLE
Reverting detour to version from release branch

### PR DESCRIPTION
**Pull request by oxtoacart**

### CODE REVIEW

**Comment by oxtoacart** [comment]
Note - if we merge this, it resolves #3545.

**Comment by myleshorton** [comment]
Thanks @oxtoacart. This could be useful for comparing making the pending detour PR clearer in terms of what it changes versus the current released code.

So #3545 was only on Valencia @oxtoacart?

**Comment by oxtoacart** [comment]
@myleshorton Yeah, #3545 was found on valencia.

**Comment by fffw** [comment]
LGTM.

**Pull request merged**
