### PR TITLE
Moved server build instructions here

### PR DESCRIPTION
**Pull request by myleshorton**

### CODE REVIEW

**Comment by myleshorton** [comment]
This looks ok @oxtoacart?

**Comment by oxtoacart** [comment]
@myleshorton Looks good.  If the user is running the build on linux, they can actually just use `make linux` instead of `make docker-linux`.

**Comment by myleshorton** [comment]
Oh good point @oxtoacart -- I'll add that.

**Comment by myleshorton** [comment]
How's it look now @oxtoacart?

**Comment by myleshorton** [comment]
Thanks @oxtoacart!

**Pull request merged**
