### PR TITLE
Release 2.2.0 devel merge

### PR DESCRIPTION
**Pull request by myleshorton**
Merging from release branch

### CODE REVIEW

**Comment by myleshorton** [comment]
Hey @atavism some of the mobile changes in this merge are a little tricky to me -- want to just take a second look when you have a chance?

**Comment by myleshorton** [comment]
Trying to just merge 2.2.0 into devel on this new branch that allowed me to first reverse merge from devel.

**Comment by atavism** [comment]
Yeah sure @myleshorton. I opened https://github.com/getlantern/lantern/pull/4241 if you want to look at it first. It fixes a few final issues I found over the weekend and adds missing translations. Then I'll close this!

**Comment by myleshorton** [comment]
Thanks @atavism!

**Pull request merged**
