### PR TITLE
Excluding feeds from all based on excludeFromAll property

### PR DESCRIPTION
**Pull request by oxtoacart**
Depends on getlantern/everfeed-combiner#18

### CODE REVIEW

**Comment by xiam** [comment]
Cool, thanks!

**Comment by atavism** [comment]
With this merged in, the articles appearing in the "all" tab no longer have summaries.

**Comment by atavism** [comment]
Ok, I fixed this on https://github.com/getlantern/lantern/pull/4154

**Comment by oxtoacart** [comment]
Sorry about that @atavism.

**Pull request merged**
