### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by oxtoacart**
This updates the dependencies for Lantern Desktop and Mobile.  That includes removing unused dependencies and upgrading remaining dependencies to latest versions (typically from master).  Needless to say, this is a pretty big change that we want to test thoroughly.

Note - there is some loss of functionality due to #3812.  Right now, I just return "Unknown 0.0" as the Android version.  This affects logging to Loggly.

### CODE REVIEW

**Comment by myleshorton** [comment]
Looks like we only use github.com/mitchellh for github.com/mitchellh/panicwrap, but we include all of github.com/mitchellh. Maybe clean that up while you're at it @oxtoacart?

This PR is exciting to me for some strange reason.

**Comment by myleshorton** [comment]
although maybe panicwrap internally relies on that..hmnn... maybe not to worry @oxtoacart

**Comment by myleshorton** [comment]
actually it doesn't look like it does need it: 

https://github.com/mitchellh/panicwrap/blob/master/panicwrap.go

**Comment by oxtoacart** [comment]
@myleshorton This PR already removes the non-panicwrap mitchelh stuff.  I basically removed everything from src/github.com other than getlantern and then refetched the needed dependencies using `go get`.

**Comment by myleshorton** [comment]
Oh cool @oxtoacart. I must have misread the diff - nice.

**Comment by myleshorton** [comment]
OK, this looks awesome to me, especially all the golang.org org updates that might actually fix a good deal. Any objections to me just merging this @oxtoacart?

**Comment by oxtoacart** [comment]
@myleshorton It's just kind of scary, but I guess devel is going to get some pretty heavy testing anyway and we can/should fail forward on this stuff anyway.  Let me try running on mobile real quick and make sure it looks happy, then we can merge.

**Comment by myleshorton** [comment]
Sounds good @oxtoacart! Yeah I agree it's a bit scary, although honestly I'm also a little frightened that we're using any of that older gomobile code in particular.

**Comment by oxtoacart** [comment]
@myleshorton Okay, mobile works, so thumbs up on pulling.

**Comment by myleshorton** [comment]
ok i'll wait for CI and then merge! detour test will probably fail again (was looking into it, and it's totally random), but that's ok. thanks @oxtoacart!

**Comment by myleshorton** [comment]
OK merging...

**Pull request merged**
