### PR TITLE
Fix for getlantern/firetweet#86

### PR DESCRIPTION
**Pull request by myleshorton**
Use getlantern/golog instead of log package and use Errorf instead of Fatalf

### CODE REVIEW

**Comment by myleshorton** [comment]
Whoops -- just fixed a few issues @fffw.

**Comment by atavism** [comment]
Seeing this:
```
../client/client.go:13: imported and not used: "github.com/getlantern/golog"
../client/client.go:52: undefined: log
../client/client.go:73: undefined: log
...
```

You need to initialize the global ``log`` var with ``golog.LoggerFor("lantern-android")`` the way we are elsewhere.

**Comment by myleshorton** [comment]
@atavism that was fixed in 474e0a6

**Comment by atavism** [comment]
OK, LGTM. Merging.

**Comment by myleshorton** [comment]
Nice thanks!

**Comment by myleshorton** [comment]
Might even be worth pushing a new FT @atavism. What do you think?

**Comment by atavism** [comment]
@myleshorton Yep. Just did.

**Comment by fffw** [comment]
Oh thanks @atavism for reviewing it. Leaved for a while at noon. Trying the new version of FT...

**Pull request merged**
