### PR TITLE
remove timeout of geolookup

### PR DESCRIPTION
**Pull request by fffw**
To stop errors in https://github.com/getlantern/lantern/issues/2394 from being reported.

### CODE REVIEW

**Comment by xiam** [comment]
Hello @fffw,

This will indeed stop timeout errors from being reported but may contribute to have idle connections (and open file descriptors). Why not increasing the timeout instead?

**Comment by fffw** [comment]
@xiam It might not be the case as OS itself has timeouts to establish a connection. But I agree to hold on this PR and dig deeper to find the root cause of frequent timeouts (cloud config fetcher didn't have so many errors).

**Comment by xiam** [comment]
Hey @fffw, would you still like to keep this one opened?

**Comment by fffw** [comment]
@xiam Thanks for mention it. Let's keep watching

**Comment by myleshorton** [comment]
I meant to comment on this one guys. In general I think we should never have sockets on either the client or server side that have no connection timeouts or read timeouts, as pretty much everything should eventually timeout, and not doing it is just begging for file limit issues.

Can you say more about OS-level timeouts @fffw? I'm unaware of any OS doing that.

On the specific case of the geolookup, I think if anything we should significantly increase the timeout. 20 seconds is way more than enough *if everything is operating normally*, but in cases of high packet loss due to anything really -- flaky local connection, flaky national connection, connecting from a plane, etc, connections can take longer than that. FireFox I believe uses 300 seconds, for example, but Lantern historically has used timeouts of around 60 seconds for things like this. I think increasing that timeout is a useful and even a necessary change.

**Comment by fffw** [comment]
In general, I think each OS should have a timeout during TCP SYN phase. I just googled a bit.

On *nix, timeout for non-established TCP connections can be obtain through`sysctl net.inet.tcp.keepinit`, which defaults to 75000 ms.

The value differs among Windows versions. https://support.microsoft.com/en-us/kb/170359 has some explanation.

A consistent timeout would be good, but I think it might be better to be applied on dialer and connection, rather than http.Client. At least, "i/o timeout" is more meaningful than "net/http: request canceled while waiting for connection"

**Pull request closed without merging**
