### PR TITLE
Lantern mobile testing

### PR DESCRIPTION
**Pull request by xiam**
Hey @atavism,

Please check this one after https://github.com/getlantern/lantern/pull/3140, tell me so I can rebase this PR.

It includes instructions on how to test the SOCKs server simulating the VpnService API to some extent on a normal Linux vm.

We don't have an easy way to simulate the "protected" call, so I am using the routing table directly.

This is similar to what I did for https://github.com/getlantern/tunio

### CODE REVIEW

**Comment by atavism** [comment]
Hey @xiam, I actually ran into the following issue running ``vagrant up``:

```
➜  lantern-mobile git:(lantern-mobile-testing) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'chef/centos-7.0' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'chef/centos-7.0' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/chef/centos-7.0"]
Error: The requested URL returned error: 404 Not Found
```

I've never used vagrant before so probably just a setup issue. Did I miss a step?

**Comment by xiam** [comment]
I think chef/ paths are no longer valid, could you try again?

**Comment by atavism** [comment]
@xiam Yep, it works now

**Comment by atavism** [comment]
Working great for me, @xiam! I'm going to go ahead and merge this. This test is extremely useful--thanks a lot!

**Pull request merged**
