### PR TITLE
Report and use IP and country from CloudFlare closes #2941

### LINKED ISSUE #2941: Use CloudFlare's geo IP lookup in flashlight servers
This will avoid using geoIP at all. We can simply return the country in a custom HTTP header (or just re-use CloudFlare's) and can also return the user's IP in a custom header.

### PR DESCRIPTION
**Pull request by myleshorton**
I just went ahead and implemented the server side of this since it's really straightforward. You want to take a look @aranhoide?

### CODE REVIEW

**Comment by aranhoide** [comment]
LGTM, tests pass in my machine.  The only nit is that IIRC we've been using the "X-Lantern-" prefix for headers instead of "Lantern-", but I won't lose any sleep over this.  Feel free to either change that or merge this PR as is.

**Comment by myleshorton** [comment]
OK merging since the X- is an old convention that's no longer recommended.

**Comment by myleshorton** [comment]
Can you deploy this when you have a chance @aranhoide?

**Comment by aranhoide** [comment]
@myleshorton done.

**Pull request merged**
