### PR TITLE
Bypassing disallowed ports in SOCKS proxy

### PR DESCRIPTION
**Pull request by fffw**
Same as https://github.com/getlantern/lantern/pull/4378. Needs more commits to fix the issue building on Windows.

### CODE REVIEW

**Comment by fffw** [comment]
Here's what `GOOS=windows go build` reports
```
./protected.go:82: cannot use socketFd (type syscall.Handle) as type int in argument to protect
./protected.go:162: cannot use socketFd (type syscall.Handle) as type int in assignment
./protected.go:198: cannot use conn.socketFd (type int) as type syscall.Handle in argument to syscall.Connect
./protected.go:231: cannot use conn.socketFd (type int) as type syscall.Handle in argument to syscall.Close
./protected.go:247: cannot use conn.socketFd (type int) as type syscall.Handle in argument to syscall.Close
```

We can't switch `socketFd` from `int` to `syscall.Handle` because `syscall.Handle` is only available on Windows.

**Comment by fffw** [comment]
One option is to make `protected` non-op on Windows, but not depending on `protected` package by default is way better.

**Comment by fffw** [comment]
@oxtoacart As your previous PR https://github.com/getlantern/lantern/pull/4378 is good to me, I'll merge this one directly with the Windows fix.

**Comment by oxtoacart** [comment]
Cool.  Thanks for fixing!

On Tuesday, May 31, 2016, fffw <notifications@github.com> wrote:

> Merged #4409 <https://github.com/getlantern/lantern/pull/4409>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/lantern/pull/4409#event-677065895>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AExNzjpGVWbj1Q0Gv9d7B8VLL60GpwQtks5qHELpgaJpZM4Ipy87>
> .
>


-- 
Cheers,
Ox

PGP Key - https://pgp.mit.edu/pks/lookup?op=get&search=ox@getlantern.org

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Pull request merged**
