### PR TITLE
Added explicit acl setting closes #2555

### LINKED ISSUE #2555: make release-beta target copies with incorrect permissions

### PR DESCRIPTION
**Pull request by myleshorton**

### CODE REVIEW

**Comment by myleshorton** [comment]
@xiam you want to take a peek at this? Just a one line change.

**Comment by xiam** [comment]
@myleshorton on it!

**Comment by xiam** [comment]
Looks good, the travis build is failing but that's a completely different problem.

**Comment by myleshorton** [comment]
Hey I just fixed a compile issue on valencia -- not totally sure how it got in there actually -- and reverse-merged here.

**Comment by myleshorton** [comment]
Yeah @xiam should be fixed now..

**Comment by xiam** [comment]
Cool, thanks. I'll just wait for the test to finish just to be sure.

**Pull request merged**
