### PR TITLE
Various 2.2.0 fixes (desktop)

### PR DESCRIPTION
**Pull request by fffw**
It includes fixes to following tickets.
#4145 hide published date if empty
#4117 respect feeds order provided by combinator
#4149 show feed name instead of site url

### CODE REVIEW

**Comment by fffw** [comment]
It also fixes #4148

**Comment by fffw** [comment]
@myleshorton a couple of simple fixes to 2.2.0.

**Comment by fffw** [comment]
Reverted https://github.com/getlantern/lantern/pull/4138 and try to fix #4108 by eliminating index operation in view.

**Comment by myleshorton** [comment]
This looks fine to me @fffw thanks!

**Pull request merged**
