### PR TITLE
Do not test cfr package, because it fails due to CloudFront deactivation

### PR DESCRIPTION
**Pull request by uaalto**
It came up in Travis

### CODE REVIEW

**Comment by xiam** [comment]
@uaalto I have seen this test failing often, do we know the reason of the failure? Would it be safe to skip it?

**Comment by myleshorton** [comment]
It fails because we've hit our cloudfront distribution limit. I've
requested an increase but its still pending approval. In general I think
it's important to test CloudFlare, but I believe Alan has a pending PR for
disabling the unused CloudFront part.

**Comment by uaalto** [comment]
I reviewed the code and found no issues in the code or potential dependencies that could be affected by that removal, so I merged it. It is a minimal change. This PR fixes the tests that failed due to deactivation, because they expect this code to be active.

This should be part of that same PR, but I didn't test this particular package because it is a 'subpackage' of peerscanner and didn't realize it had its own separate tests until I saw it on Travis. That's why it's an independent PR.

**Comment by myleshorton** [comment]
Oh right sorry @uaalto I didn't realize CloudFront had it's own package. Looks great!

**Comment by uaalto** [comment]
thank you! I didn't realize either @myleshorton  :)

**Pull request merged**
