### PR TITLE
Improved test coverage

### PR DESCRIPTION
**Pull request by oxtoacart**
By:

- Adding integration test
- Removing unused packages
- Making sure that we're counting coverage for all packages when we run any test

This is the real PR, but there's a simplified version at #3978 that focuses just on substantial code changes.

### CODE REVIEW

**Comment by myleshorton** [comment]
It's a little hard to tell from the diff @oxtoacart but does this delete the measured package? If so I just want to make sure any changes in it are pushed upstream because I believe @uaalto is using that in http-proxy-lantern as well.

**Comment by oxtoacart** [comment]
@myleshorton This actually adds measured because it's needed by http-proxy-lantern, which I'm including for purposes of integration testing.

**Comment by myleshorton** [comment]
oh cool thanks @oxtoacart

**Comment by myleshorton** [comment]
Hmn...looks like the test is failing on FinestWebView-Android submodule -- weird. Otherwise this looks great @oxtoacart and ready to merge.

**Comment by oxtoacart** [comment]
@myleshorton The tests are passing in Travis.  Are you running a test locally that's failing?

**Comment by myleshorton** [comment]
No -- the tests for this PR are failing.

**Comment by oxtoacart** [comment]
@myleshorton PR build is green.  Thanks for the review!

**Comment by myleshorton** [comment]
Thank you @oxtoacart!

**Pull request merged**
