### PR TITLE
delete "douyutv.com" from "proxiedsites" #3873

### PR DESCRIPTION
**Pull request by kehao95**
delete "douyutv.com" from "proxiedsites" #3873

### CODE REVIEW

**Comment by fffw** [comment]
LGTM. Though it will not take effect until we run genconfig again next time.

**Comment by myleshorton** [comment]
This needs to also be deleted in lantern_aws unfortunately @fffw -- otherwise the global sites will overwrite this while running lantern.

**Comment by fffw** [comment]
Did that in https://github.com/getlantern/lantern_aws/commit/e29416ab386628bab13157b344a498424a9b135e. Thanks @myleshorton !

**Comment by fffw** [comment]
As we plan to host common configuration separately on cloud, we can also always fetch latest configuration from cloud when building Lantern. By this way we don't need to have two copies of some list.

**Pull request merged**
