### PR TITLE
get feed through Lantern in integration test

### LINKED ISSUE #4114: `getlantern/lantern` test failed
https://travis-ci.org/getlantern/lantern/builds/126314302

> === RUN   TestGetFeed
> Apr 28 08:10:10.527 - 0m3s ERROR lantern: feed.go:104 Unable to open gzip reader: gzip: invalid header
> --- FAIL: TestGetFeed (3.22s)
> 	Error Trace:	feed_test.go:30
> 			feed_test.go:45
> 	Error:		Expected value not to be nil.
> 		
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xb code=0x1 addr=0x10 pc=0x4ac97d]
> goroutine 24 [running]:
> panic(0xbbf3a0, 0xc820016160)
> 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3ff
> testing.tRunner.func1(0xc82009e1b0)
> 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:467 +0x22a
> panic(0xbbf3a0, 0xc820016160)
> 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:426 +0x521
> github.com/getlantern/lantern.NumFeedEntries(0x0)
> 	github.com/getlantern/lantern/_test/_obj_test/feed.go:91 +0x6d
> github.com/getlantern/lantern.getFeed(0xc82009e1b0, 0xc788f0, 0x5)
> 	/home/travis/gopath/src/github.com/getlantern/lantern/src/github.com/getlantern/lantern/feed_test.go:37 +0x37e
> github.com/getlantern/lantern.TestGetFeed(0xc82009e1b0)
> 	/home/travis/gopath/src/github.com/getlantern/lantern/src/github.com/getlantern/lantern/feed_test.go:45 +0x129
> testing.tRunner(0xc82009e1b0, 0x124e080)
> 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0xdd
> created by testing.RunTests
> 	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:582 +0xae3
> exit status 2
> FAIL	github.com/getlantern/lantern	3.311s
> make: *** [test-and-cover] Error 1
>

### PR DESCRIPTION
**Pull request by fffw**
Lantern will try detour when fail to dial direct connection, hence reduce the chance of failed test. Fix #4114

### CODE REVIEW

**Comment by fffw** [comment]
@atavism You probably want to take a look?

**Comment by oxtoacart** [comment]
@fffw For tests like this, I think it's best to make them independent of the internet and out server infrastructure, so I suggest this - https://github.com/getlantern/lantern/pull/4162

**Comment by fffw** [comment]
@oxtoacart If they are actual integration tests, we can add `+build integration` flag to the .go files to avoid run it in Travis. That raises the question of how we automate the integration tests to tolerant small percentage of failures.

**Comment by atavism** [comment]
Given that we ended up merging in [4162](https://github.com/getlantern/lantern/pull/4162) for this already, I'm going to close this. Thanks though, @fffw!

**Pull request closed without merging**
