### PR TITLE
Added putting beta releases in GitHub as well closes #2633

### LINKED ISSUE #2633: Also copy betas to lantern-binaries repo in make release beta
When we deploy betas, it would also be useful to deploy to the following URLs in case of S3 blocking:

https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.dmg
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-32-bit.deb
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-64-bit.deb

### PR DESCRIPTION
**Pull request by myleshorton**
I just knocked this out while releasing beta 6. Can you review @xiam?

### CODE REVIEW

**Comment by xiam** [comment]
Thanks a lot @myleshorton! Sorry I was not able to take a stab at that one but I'm taking a look at the pr. Hope to get a conclusion on #2184 soon.

**Comment by myleshorton** [comment]
Cool and no worries at all @xiam!

**Comment by xiam** [comment]
Looks good to me, tests are failing for other reasons.

**Comment by myleshorton** [comment]
thanks @xiam!

**Pull request merged**
