### PR TITLE
Multicast discovery

### PR DESCRIPTION
**Pull request by uaalto**
Provide discovery of Lantern processes in the local network through SSM multicast.
This module is a step towards https://github.com/getlantern/lantern/issues/2462
* It's prepared for integration through AddPeer/RemovePeer callbacks.
* Provides tests, and a testing command that can be run standalone to check for discovery

Tested on Raspberry Pi and/with OSX

### CODE REVIEW

**Comment by atavism** [comment]
@uaalto Great, thanks! I will look over this as I have a Raspberry Pi 2 already (that's what powers the Lantern Pi as I said). Were there any changes to the [Makefile](https://github.com/getlantern/lantern/blob/valencia/Makefile) related to https://github.com/getlantern/lantern/issues/2463? i.e. do we have a new ARM target and linux-arm package that are generated now for instance?

**Comment by uaalto** [comment]
This module is currently not integrated within Lantern, and can be tested independently. You can test the discovery and the add/remove callbacks with the command found in /cmd. No changes were necessary to the Makefile. Since integration requires changing Lantern UI we will need to talk about how to approach it. I will next work on the ARM port though.

**Comment by myleshorton** [comment]
Sounds great @uaalto. In the natty beta releases we just put locally-discovered Lantern Pis in the advanced settings in the UI. Do you happen to have a screenshot of that kicking around @atavism? Those installers are here @uaalto:

https://s3.amazonaws.com/lantern/lantern-natty-0.0.3.dmg
https://s3.amazonaws.com/lantern/lantern-natty-0.0.3.exe
https://s3.amazonaws.com/lantern/lantern-natty-0.0.3-32-bit.deb
https://s3.amazonaws.com/lantern/lantern-natty-0.0.3-64-bit.deb

**Comment by uaalto** [comment]
Ok! But, once this discovered Lantern Pi's are displayed, do we give the possibility to connect to them with the administration interface?

**Comment by uaalto** [comment]
Also, I've just committed a subtle fix that was bugging me: I assumed that SSM multicast was being used due to the address used in the reference implementation (232.77.77.77), but actually the multicast implementation didn't (and doesn't) use source-specific multicast. Even though the issue is not noticeable in practice, we would be using a wrong multicast address.

**Comment by myleshorton** [comment]
Yeah -- it just includes a link to open the Lantern dashboard on the Pi. That also requires a change to not bind the HTTP server to localhost.

**Comment by atavism** [comment]
@myleshorton Yes, I just found it:

image

**Comment by uaalto** [comment]
Thank you!

**Pull request closed without merging**
