### PR TITLE
Updating Dockerfile, gomobile was failing

### PR DESCRIPTION
**Pull request by xiam**
Should be a quick one, could you give a look @uaalto?

### CODE REVIEW

**Comment by uaalto** [comment]
The code looks good, but it fails with
```
--- FAIL: TestCloneNEWUSERAndRemapRootDisableSetgroups (0.00s)
        exec_linux_test.go:53: Cmd failed with err fork/exec /usr/bin/whoami: operation not permitted, output: 
--- FAIL: TestCloneNEWUSERAndRemapRootEnableSetgroups (0.00s)
        exec_linux_test.go:53: Cmd failed with err fork/exec /usr/bin/whoami: operation not permitted, output: 
```

**Comment by xiam** [comment]
I tried again with a clean boot2docker installation and works fine. Does it happen every time @uaalto? Do you also have the same result when trying to use `make android-lib` @fffw?

**Comment by fffw** [comment]
Hanging at `Step 8 : RUN dnf -y update && dnf clean all`. Will try from another ISP 1 hour later.

**Comment by uaalto** [comment]
Hey @xiam. It fails exactly the same way. I'm going to try with a clean remake, but it shouldn't make a difference.

**Comment by uaalto** [comment]
Same thing, after remaking all images from scratch.
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

**Comment by xiam** [comment]
Do you think this could be due to some memory constraint on the host?

**Comment by uaalto** [comment]
It's possible! I rebuilt it in a beefier machine and works (OSX)

**Comment by uaalto** [comment]
Ready for merge?

**Comment by xiam** [comment]
Awesome! thanks for testing. Please go on and merge it :)

**Comment by uaalto** [comment]
LGTM! Thanks

**Comment by fffw** [comment]
`make android-lib` ate up the space of `boot2docker` VM so I have to remove lots of Docker images to restart. Just want to say that finally it works!

**Pull request merged**
