### PR TITLE
Stop Lantern when user disconnects from WiFi network

### PR DESCRIPTION
**Pull request by atavism**
This registers a new broadcast receiver that detects changes in network connectivity. If Lantern is running, and we disconnect from Wi-Fi, we automatically turn off the VPN service.

### CODE REVIEW

**Comment by oxtoacart** [comment]
In my testing, the VPN service does indeed stop when I disable the network.

**Comment by oxtoacart** [comment]
If I disable wifi while I'm in the app, the slider doesn't change to show that Lantern is actually off.

**Comment by oxtoacart** [comment]
With the exception of that one small usability niggle, this works for me.  Merging.

**Comment by myleshorton** [comment]
Nice! So does this mean we can push out a new mobile build @oxtoacart and @atavism?

**Comment by oxtoacart** [comment]
@myleshorton Yes!

**Pull request merged**
