### PR TITLE
Windows Firewall configuration (and Go library)

### LINKED ISSUE #2949: Set up Firewall rules in Windows for incoming connections
This will be necessary for give mode.

https://github.com/getlantern/lantern-java/blob/master/install/win/Lantern.bat

### PR DESCRIPTION
**Pull request by uaalto**
Closes #2949 

The code is mostly C, embedded in Go. The interface is simple to use from Go, but the internals required a lot of fiddling, and due to Go's strict type rules and lack of C macro support among other things, it was necessary to implement the lower layer in C and have full control.

The library should support from Windows XP to Windows 10.

On the Lantern program side, the visible part to the user is this:
1. Test if the Firewall is either off or has a rule for Lantern
2. If any of these is true means that Lantern will need to set up a rule. This needs to be done with Admin privileges.

### CODE REVIEW

**Comment by xiam** [comment]
Hey @uaalto, I'm checking Windows right now, is this still relevant? What do we need this for?

**Comment by wangbo4020** [comment]
告诉大家一个秘密。
开着Lantern打LOL会卡，所以要关掉。
“代理全部流量”没有选。

**Comment by robot1d59cc305** [comment]
I am a paying user of the Lantern, but recently I had a problem licensing the professional version of the Lantern for my Android phone.
Whenever I want to enter the "dynamic authorization code" given to me by the Android Lantern into the "authorize other devices to use professional" dialog box on Windows, I can now run the Android Lantern at any time.
The "authorization device for professional use" interface of the Android Lantern client always pops up "error of obtaining dynamic authorization code"!Please try again later."Such content prevented me from turning the Android Lantern into a professional version.
How to solve this problem?On my Windows system, where the Lantern professional edition can be used normally, I purchased a two-year professional edition of the service, which now runs out next year.

 [help](https://wx4.sinaimg.cn/mw690/006ZJqdEly8fyteotbea0j30k016876g.jpg)

**Comment by pengyuan** [comment]
请蓝灯客服留下联系方式。

我去年买了三年的蓝灯专业版，有不限制的高速流量，也有提示到期日期为2021年。
结果最新版本要求我升级到5.2，而且没有了到期日期，每次连接说我高速流量已用完，要求升级隐币。

以后还有谁敢买专业版，我之前的费用到哪里去了？？？
求解释！！！！！！

**Pull request closed without merging**
