### PR TITLE
Uniform fallbacks json

### PR DESCRIPTION
**Pull request by aranhoide**
Remove minor differences between the fallbacks.json format, which is generated in the fallbacks themselves, and the configuration that goes into cloud.yaml, which is a serialization of `client.ChainedServerInfo`.  A complementary PR will be made for lantern_aws.

### CODE REVIEW

**Comment by uaalto** [comment]
It's straightforward and I see no potential issue. It simplifies and unifies the code. LGTM.
Should I go on and merge this? (asking since this is server code).

**Comment by myleshorton** [comment]
Yeah I would say feel free to just merge it.

**Comment by uaalto** [comment]
Great! LGTM. Thanks @myleshorton and @aranhoide

**Comment by aranhoide** [comment]
Thanks!  Sorry I have totally broken sleep schedules.  This was actually already deployed since, besides being straightforward as you say, at the moment this stuff is only triggered manually and it's kind of self-checking.

**Pull request merged**
